# Criar o Índice
curl -X PUT  http://elastic:changeme@192.168.0.112:9200/usuarios
 ## MUDAR O IP
### 
curl -X PUT  http://elastic:changeme@192.168.0.112:9200/covid


###
# Pegar o documento
GET http://elastic:changeme@192.168.0.112:9200/usuarios/_doc/v9WOEnoBMhAar20Z6FjH

###
# Criar um documento
POST http://elastic:changeme@192.168.0.112:9200/usuarios/_doc  HTTP/1.1
content-type: application/json

{
   "nome":"livia", 
   "cargo":"mecatronica"
}

###
# Lista os documentos
GET http://elastic:changeme@192.168.0.112:9200/usuarios/_search
